### ISSUE TITLE
package-install-file fails

### ISSUE THREAD

**Issue by DavidBiesack** [purcell/exec-path-from-shell#38]
I tried the Installation step after downloading and saving the file. 

The installation instructions are wrong (`M-x package-install-from-file` should be `M-x package-install-file`)

After running `M-x package-install-file`, I got an error:

```
package-buffer-info: Package lacks a "Version" or "Package-Version" header
```

`M-x emacs-version` reports:
```
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org
```

**Comment by DavidBiesack** [comment]
BTW, my copy of the file does contain
```

;; Author: Steve Purcell <steve@sanityinc.com>
;; Keywords: environment
;; URL: https://github.com/purcell/exec-path-from-shell
;; Version: DEV
```

**Comment by purcell** [comment]
Thanks David: 5e80a41 should fix that.

**Comment by DavidBiesack** [comment]
Thanks. The installation instructions in README are still wrong (`M-x package-install-from-file` should be `M-x package-install-file`)

**Comment by purcell** [comment]
Fixed, thanks.

**Comment by DavidBiesack** [comment]
doc looks good.

``package-install-file`` now works correctly. Thanks

**Comment by qwert42** [comment]
Maybe you could make a release for this commit? I notice that the latest release was on Oct 7, 2015.

Thanks!

**Comment by purcell** [comment]
Done. Thanks for the reminder.
